BEGIN;

DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS field_prices CASCADE;
DROP TABLE IF EXISTS field_images CASCADE;
DROP TABLE IF EXISTS fields CASCADE;
DROP TABLE IF EXISTS time_slots CASCADE;
DROP TABLE IF EXISTS owners CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS booking_status;
DROP TYPE IF EXISTS field_status;
DROP TYPE IF EXISTS user_role;

CREATE TYPE booking_status AS ENUM ('pending', 'approved', 'rejected', 'cancelled');
CREATE TYPE field_status AS ENUM ('active', 'inactive');
CREATE TYPE user_role AS ENUM ('customer', 'owner', 'admin');

CREATE TABLE users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clerk_user_id varchar(255) NOT NULL UNIQUE,
  name varchar(100),
  email varchar(150),
  phone varchar(20),
  role user_role NOT NULL,
  created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE owners (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL UNIQUE,
  owner_name varchar(100) NOT NULL,
  phone varchar(20) NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT fk_owner_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE fields (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  field_name varchar(100) NOT NULL,
  address varchar(255) NOT NULL,
  description text,
  owner_id integer NOT NULL,
  status field_status DEFAULT 'active',
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT fk_field_owner FOREIGN KEY (owner_id) REFERENCES owners(id) ON DELETE CASCADE
);

CREATE TABLE field_images (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  field_id integer NOT NULL,
  image_url varchar(255) NOT NULL,
  is_primary boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT fk_image_field FOREIGN KEY (field_id) REFERENCES fields(id) ON DELETE CASCADE
);

CREATE TABLE reviews (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id integer NOT NULL,
  field_id integer NOT NULL,
  rating integer CHECK (rating BETWEEN 1 AND 5),
  comment text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT fk_review_field FOREIGN KEY (field_id) REFERENCES fields(id) ON DELETE CASCADE
);

CREATE TABLE bookings (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id integer NOT NULL,
  field_id integer NOT NULL,
  booking_date date NOT NULL,
  start_time time NOT NULL,
  end_time time NOT NULL,
  contact_phone varchar(20) NOT NULL,
  note text,
  total_price numeric(10,2) NOT NULL,
  status booking_status DEFAULT 'pending',
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT uq_bookings_field_date_start UNIQUE (field_id, booking_date, start_time),
  CONSTRAINT fk_booking_customer FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_booking_field FOREIGN KEY (field_id) REFERENCES fields(id) ON DELETE CASCADE
);

CREATE INDEX idx_bookings_customer_id ON bookings(customer_id);
CREATE INDEX idx_fields_owner_id ON fields(owner_id);
CREATE INDEX idx_field_images_field_id ON field_images(field_id);
CREATE INDEX idx_reviews_field_id ON reviews(field_id);

-- Dữ liệu mẫu (Tùy chọn)
INSERT INTO users (clerk_user_id, name, email, role) VALUES
('user_admin', 'Admin', 'admin@gmail.com', 'admin');

COMMIT;
