BEGIN;

DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS field_prices CASCADE;
DROP TABLE IF EXISTS field_images CASCADE;
DROP TABLE IF EXISTS fields CASCADE;
DROP TABLE IF EXISTS time_slots CASCADE;
DROP TABLE IF EXISTS owners CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS booking_status;
DROP TYPE IF EXISTS field_status;
DROP TYPE IF EXISTS time_slot_type;
DROP TYPE IF EXISTS user_role;

CREATE TYPE booking_status AS ENUM ('pending', 'approved', 'rejected', 'cancelled');
CREATE TYPE field_status AS ENUM ('active', 'inactive');
CREATE TYPE time_slot_type AS ENUM ('normal', 'peak');
CREATE TYPE user_role AS ENUM ('customer', 'owner', 'admin');

CREATE TABLE users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clerk_user_id varchar(255) NOT NULL UNIQUE,
  name varchar(100),
  email varchar(150),
  phone varchar(20),
  role user_role NOT NULL,
  created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE owners (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL UNIQUE,
  owner_name varchar(100) NOT NULL,
  phone varchar(20) NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT fk_owner_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE fields (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  field_name varchar(100) NOT NULL,
  province varchar(100) NOT NULL,
  district varchar(100) NOT NULL,
  ward varchar(100) NOT NULL,
  street_address varchar(255) NOT NULL,
  description text,
  owner_id integer NOT NULL,
  status field_status DEFAULT 'active',
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT fk_field_owner FOREIGN KEY (owner_id) REFERENCES owners(id) ON DELETE CASCADE
);

CREATE TABLE time_slots (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_time time NOT NULL,
  end_time time NOT NULL,
  type time_slot_type DEFAULT 'normal'
);

CREATE TABLE field_images (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  field_id integer NOT NULL,
  image_url varchar(255) NOT NULL,
  is_primary boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT fk_image_field FOREIGN KEY (field_id) REFERENCES fields(id) ON DELETE CASCADE
);

CREATE TABLE field_prices (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  field_id integer NOT NULL,
  time_slot_id integer NOT NULL,
  price numeric(10,2) NOT NULL,
  CONSTRAINT uq_field_prices_field_slot UNIQUE (field_id, time_slot_id),
  CONSTRAINT fk_price_field FOREIGN KEY (field_id) REFERENCES fields(id) ON DELETE CASCADE,
  CONSTRAINT fk_price_time FOREIGN KEY (time_slot_id) REFERENCES time_slots(id) ON DELETE CASCADE
);

CREATE TABLE reviews (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id integer NOT NULL,
  field_id integer NOT NULL,
  rating integer CHECK (rating BETWEEN 1 AND 5),
  comment text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT fk_review_field FOREIGN KEY (field_id) REFERENCES fields(id) ON DELETE CASCADE
);

CREATE TABLE bookings (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id integer NOT NULL,
  field_id integer NOT NULL,
  time_slot_id integer NOT NULL,
  booking_date date NOT NULL,
  contact_phone varchar(20) NOT NULL,
  note text,
  total_price numeric(10,2) NOT NULL,
  status booking_status DEFAULT 'pending',
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT uq_bookings_field_date_slot UNIQUE (field_id, booking_date, time_slot_id),
  CONSTRAINT fk_booking_customer FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_booking_field FOREIGN KEY (field_id) REFERENCES fields(id) ON DELETE CASCADE,
  CONSTRAINT fk_booking_time FOREIGN KEY (time_slot_id) REFERENCES time_slots(id) ON DELETE CASCADE
);

CREATE INDEX idx_bookings_customer_id ON bookings(customer_id);
CREATE INDEX idx_bookings_time_slot_id ON bookings(time_slot_id);
CREATE INDEX idx_fields_owner_id ON fields(owner_id);
CREATE INDEX idx_field_images_field_id ON field_images(field_id);
CREATE INDEX idx_field_prices_time_slot_id ON field_prices(time_slot_id);
CREATE INDEX idx_reviews_field_id ON reviews(field_id);

INSERT INTO users (id, clerk_user_id, name, email, phone, role, created_at) VALUES
(1, '', 'Admin', 'admin@gmail.com', NULL, 'admin', '2026-01-29 22:21:56'),
(7, 'user_394jsFqCB3KdkBbm0GpF4FQANdF', 'Tien Pham', 'ngoctien30804@gmail.com', NULL, 'owner', '2026-02-01 23:14:05'),
(9, 'user_394jv4J9a2pDwoVuw67rghzpHg8', 'Tien', 'trieng02@gmail.com', NULL, 'customer', '2026-02-05 17:19:12');

INSERT INTO owners (id, user_id, owner_name, phone, created_at) VALUES
(2, 7, 'Tien Pham', '', '2026-02-01 23:29:15');

INSERT INTO fields (id, field_name, province, district, ward, street_address, description, owner_id, status, created_at) VALUES
(3, 'San bong Tuan Phong', 'Ha Noi', 'Thanh Xuan', 'Thanh Tri', 'Duong Pham Tu, so 10', 'San choi cho anh em dam me bong da', 2, 'active', '2026-02-01 23:29:15'),
(4, 'San bong Minh Duc', 'Ha Noi', 'Thanh Xuan', 'Thanh Tri', 'Duong Pham Tu, so 12', 'San bong da chat luong', 2, 'active', '2026-02-05 17:24:33');

INSERT INTO field_images (id, field_id, image_url, is_primary, created_at) VALUES
(3, 3, '/uploads/1769963355774-sh5awcbe.jpg', true, '2026-02-01 23:29:15'),
(4, 4, '/uploads/1770287073797-sa2hqaw9.jpg', true, '2026-02-05 17:24:33');

INSERT INTO time_slots (id, start_time, end_time, type) VALUES
(1, '17:00:00', '18:00:00', 'peak'),
(2, '18:00:00', '19:00:00', 'peak'),
(3, '17:00:00', '18:30:00', 'peak'),
(4, '18:30:00', '20:00:00', 'peak');

INSERT INTO field_prices (id, field_id, time_slot_id, price) VALUES
(1, 3, 1, 1000000.00),
(2, 3, 2, 1000000.00),
(3, 4, 3, 1000000.00),
(4, 4, 4, 1000000.00);

INSERT INTO reviews (id, customer_id, field_id, rating, comment, created_at) VALUES
(1, 9, 3, 5, 'te', '2026-02-05 17:46:43'),
(6, 9, 3, 3, 'ok', '2026-02-05 17:55:35'),
(7, 9, 4, 5, 'oki', '2026-02-14 14:07:37');

SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1), true);
SELECT setval(pg_get_serial_sequence('owners', 'id'), COALESCE((SELECT MAX(id) FROM owners), 1), true);
SELECT setval(pg_get_serial_sequence('fields', 'id'), COALESCE((SELECT MAX(id) FROM fields), 1), true);
SELECT setval(pg_get_serial_sequence('field_images', 'id'), COALESCE((SELECT MAX(id) FROM field_images), 1), true);
SELECT setval(pg_get_serial_sequence('field_prices', 'id'), COALESCE((SELECT MAX(id) FROM field_prices), 1), true);
SELECT setval(pg_get_serial_sequence('reviews', 'id'), COALESCE((SELECT MAX(id) FROM reviews), 1), true);
SELECT setval(pg_get_serial_sequence('time_slots', 'id'), COALESCE((SELECT MAX(id) FROM time_slots), 1), true);
SELECT setval(pg_get_serial_sequence('bookings', 'id'), COALESCE((SELECT MAX(id) FROM bookings), 1), true);

COMMIT;
