BEGIN;

-- Extensions for accent-insensitive search and fast ILIKE
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS conversations CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS review_replies CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS field_prices CASCADE;
DROP TABLE IF EXISTS field_images CASCADE;
DROP TABLE IF EXISTS fields CASCADE;
DROP TABLE IF EXISTS time_slots CASCADE;
DROP TABLE IF EXISTS owners CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS booking_status;
DROP TYPE IF EXISTS field_status;
DROP TYPE IF EXISTS user_role CASCADE;

CREATE TYPE booking_status AS ENUM ('pending', 'approved', 'rejected', 'cancelled');
CREATE TYPE field_status AS ENUM ('active', 'inactive');
CREATE TYPE user_role AS ENUM ('customer', 'owner', 'admin');

CREATE TABLE users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clerk_user_id varchar(255) NOT NULL UNIQUE,
  name varchar(100),
  email varchar(150),
  phone varchar(20),
  role user_role NOT NULL,
  owner_approved boolean NOT NULL DEFAULT true,
  is_locked boolean NOT NULL DEFAULT false,
  deleted_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE owners (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL UNIQUE,
  owner_name varchar(100) NOT NULL,
  phone varchar(20) NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT fk_owner_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE fields (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  field_name varchar(100) NOT NULL,
  address varchar(255) NOT NULL,
  description text,
  owner_id integer NOT NULL,
  status field_status DEFAULT 'active',
  -- Normalized search columns: lower + bỏ dấu (accent-insensitive)
  -- Note: cannot be GENERATED columns because unaccent() is STABLE (not IMMUTABLE).
  field_name_search text,
  address_search text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT fk_field_owner FOREIGN KEY (owner_id) REFERENCES owners(id) ON DELETE CASCADE
);

CREATE INDEX idx_fields_field_name_search_trgm ON fields USING gin (field_name_search gin_trgm_ops);
CREATE INDEX idx_fields_address_search_trgm ON fields USING gin (address_search gin_trgm_ops);

CREATE OR REPLACE FUNCTION fields_set_search_columns()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.field_name_search := unaccent(lower(COALESCE(NEW.field_name, '')));
  NEW.address_search := unaccent(lower(COALESCE(NEW.address, '')));
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_fields_set_search_columns
BEFORE INSERT OR UPDATE OF field_name, address ON fields
FOR EACH ROW
EXECUTE FUNCTION fields_set_search_columns();

CREATE TABLE field_images (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  field_id integer NOT NULL,
  image_url varchar(255) NOT NULL,
  is_primary boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT fk_image_field FOREIGN KEY (field_id) REFERENCES fields(id) ON DELETE CASCADE
);

CREATE TABLE reviews (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id integer NOT NULL,
  field_id integer NOT NULL,
  rating integer CHECK (rating BETWEEN 1 AND 5),
  comment text,
  owner_reply text,
  owner_reply_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT fk_review_customer FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_review_field FOREIGN KEY (field_id) REFERENCES fields(id) ON DELETE CASCADE
);

CREATE TABLE review_replies (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id integer NOT NULL,
  owner_id integer NOT NULL,
  reply text NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT fk_review_reply_review FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE,
  CONSTRAINT fk_review_reply_owner FOREIGN KEY (owner_id) REFERENCES owners(id) ON DELETE CASCADE
);

CREATE TABLE bookings (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id integer NOT NULL,
  field_id integer NOT NULL,
  booking_date date NOT NULL,
  start_time time NOT NULL,
  end_time time NOT NULL,
  contact_phone varchar(20) NOT NULL,
  note text,
  total_price numeric(10,2) NOT NULL,
  status booking_status DEFAULT 'pending',
  payment_status varchar(20) NOT NULL DEFAULT 'unpaid',
  payment_method varchar(50),
  paid_at timestamp without time zone,
  cancelled_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT fk_booking_customer FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_booking_field FOREIGN KEY (field_id) REFERENCES fields(id) ON DELETE CASCADE
);

-- Only prevent double-booking for active statuses
CREATE UNIQUE INDEX uq_bookings_active_field_date_start
ON bookings (field_id, booking_date, start_time)
WHERE status IN ('pending', 'approved');

CREATE INDEX idx_bookings_customer_id ON bookings(customer_id);
CREATE INDEX idx_fields_owner_id ON fields(owner_id);
CREATE INDEX idx_field_images_field_id ON field_images(field_id);
CREATE INDEX idx_reviews_field_id ON reviews(field_id);
CREATE INDEX idx_reviews_customer_id ON reviews(customer_id);
CREATE INDEX idx_review_replies_review_id ON review_replies(review_id);
CREATE INDEX idx_review_replies_owner_id ON review_replies(owner_id);

CREATE TABLE conversations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  field_id integer NOT NULL,
  customer_id integer NOT NULL,
  owner_user_id integer NOT NULL,
  last_message text,
  last_message_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT uq_conversation_field_customer_owner UNIQUE (field_id, customer_id, owner_user_id),
  CONSTRAINT fk_conversation_field FOREIGN KEY (field_id) REFERENCES fields(id) ON DELETE CASCADE,
  CONSTRAINT fk_conversation_customer FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_conversation_owner_user FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_conversations_customer_id ON conversations(customer_id);
CREATE INDEX idx_conversations_owner_user_id ON conversations(owner_user_id);
CREATE INDEX idx_conversations_field_id ON conversations(field_id);

CREATE TABLE messages (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id integer NOT NULL,
  sender_user_id integer NOT NULL,
  sender_role user_role NOT NULL,
  content text NOT NULL,
  read_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT fk_message_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
  CONSTRAINT fk_message_sender FOREIGN KEY (sender_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_messages_conversation_id ON messages(conversation_id);

-- Migration: add booking_services table to store extra services attached to each booking

CREATE TABLE IF NOT EXISTS booking_services (
    id SERIAL PRIMARY KEY,
    booking_id INTEGER NOT NULL,
    name VARCHAR(150) NOT NULL,
    unit_price NUMERIC(10,2) NOT NULL DEFAULT 0,
    quantity INTEGER NOT NULL DEFAULT 1,
    total_price NUMERIC(10,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_booking_services_booking
        FOREIGN KEY (booking_id)
        REFERENCES bookings(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_booking_services_booking_id
    ON booking_services (booking_id);

-- Dữ liệu mẫu (Tùy chọn)
-- No default admin user; only customer and owner roles are used

COMMIT;
