-- Reviews: allow multiple reviews per customer per field
-- Owner replies: allow multiple replies per review

-- 1) Drop the unique constraint if it exists (Postgres/Supabase)
ALTER TABLE reviews
  DROP CONSTRAINT IF EXISTS uq_reviews_customer_field;

-- 2) Create replies table
CREATE TABLE IF NOT EXISTS review_replies (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id integer NOT NULL REFERENCES reviews(id) ON DELETE CASCADE,
  owner_id integer NOT NULL REFERENCES owners(id) ON DELETE CASCADE,
  reply text NOT NULL,
  created_at timestamp without time zone DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_review_replies_review_id ON review_replies(review_id);
CREATE INDEX IF NOT EXISTS idx_review_replies_owner_id ON review_replies(owner_id);

